name: "Integration tests"

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [opened, synchronize]
    branches: [ master ]

jobs:
  TestWithoutProjectMining:
    runs-on: ubuntu-latest
    name: Integration Tests without project mining
    steps:
    - name: Checkout repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

    - name: Set up Python
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Collect data for Integration tests
      id: collect_data_without_project
      uses: AbsaOSS/living-doc-collector-gh@3992722e3b7c547e8557a794cbe42d5413326dae
      env:
        GITHUB_TOKEN: ${{ secrets.REPOSITORIES_TOKEN }}
      with:
        GITHUB-TOKEN: ${{ secrets.REPOSITORIES_TOKEN }}
        doc-issues: true
        verbose-logging: true

        doc-issues-repositories: |
          [
            {
              "organization-name": "AbsaOSS",
              "repository-name": "living-doc-generator-mdoc",
              "projects-title-filter": [] 
            }
          ]
        doc-issues-project-state-mining: false

    - name: Integration test
      id: generate_living_doc_1
      env:
        INPUT_SOURCE: "${{ steps.collect_data_without_project.outputs.output-path }}/doc-issues/doc-issues.json"
        INPUT_RELEASE: "false"
        INPUT_STRUCTURED_OUTPUT: "false"
        INPUT_REPORT_PAGE: "true"
        INPUT_VERBOSE_LOGGING: "true"
      run: |
        rm -rf output/generator
        python main.py
        echo "output-path=$PWD/output/generator/mdoc" >> "$GITHUB_OUTPUT"

    - name: Show generated output
      run: ls -lR "${{ steps.generate_living_doc_1.outputs.output-path }}"

    - name: Verify integration test results
      run: pytest tests/integration/validate_outputs_test.py::test_validate_for_test_without_project_mining

  TestsWithProjectMining:
    runs-on: ubuntu-latest
    name: Integration Tests with project mining
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Set up Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect data with Project for Integration tests
        id: collect_data_with_project_1
        uses: AbsaOSS/living-doc-collector-gh@3992722e3b7c547e8557a794cbe42d5413326dae
        env:
          GITHUB_TOKEN: ${{ secrets.REPOSITORIES_TOKEN }}
        with:
          GITHUB-TOKEN: ${{ secrets.REPOSITORIES_TOKEN }}
          doc-issues: true
          verbose-logging: true

          doc-issues-repositories: |
            [
              {
                "organization-name": "AbsaOSS",
                "repository-name": "living-doc-generator-mdoc",
                "projects-title-filter": []
              }
            ]
          doc-issues-project-state-mining: true

      - name: Integration test
        id: generate_living_doc_1
        env:
          GITHUB_TOKEN: ${{ secrets.REPOSITORIES_TOKEN }}
          INPUT_SOURCE: "${{ steps.collect_data_with_project_1.outputs.output-path }}/doc-issues/doc-issues.json"
          INPUT_RELEASE: "false"
          INPUT_STRUCTURED_OUTPUT: "false"
          INPUT_REPORT_PAGE: "true"
          INPUT_VERBOSE_LOGGING: "true"
        run: |
          rm -rf output/generator
          python main.py
          echo "output-path=$PWD/output/generator/mdoc" >> "$GITHUB_OUTPUT"

      - name: Show generated output
        run: ls -lR "${{ steps.generate_living_doc_1.outputs.output-path }}"

      - name: Verify integration test results
        run: pytest tests/integration/validate_outputs_test.py::test_validate_for_test_with_project_mining

  TestWithProjectMiningExcludeProject:
    runs-on: ubuntu-latest
    name: Integration Tests with project mining and excluded project
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Set up Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect data with Project for Integration tests
        id: collect_data_with_project_2
        uses: AbsaOSS/living-doc-collector-gh@3992722e3b7c547e8557a794cbe42d5413326dae
        env:
          GITHUB_TOKEN: ${{ secrets.REPOSITORIES_TOKEN }}
        with:
          GITHUB-TOKEN: ${{ secrets.REPOSITORIES_TOKEN }}
          doc-issues: true
          verbose-logging: true

          doc-issues-repositories: |
            [
              {
                "organization-name": "AbsaOSS",
                "repository-name": "living-doc-generator-mdoc",
                "projects-title-filter": ["integration-tests-for-living-doc-generator"]
              }
            ]
          doc-issues-project-state-mining: true

      - name: Integration test
        id: generate_living_doc_2
        env:
          GITHUB_TOKEN: ${{ secrets.REPOSITORIES_TOKEN }}
          INPUT_SOURCE: "${{ steps.collect_data_with_project_2.outputs.output-path }}/doc-issues/doc-issues.json"
          INPUT_RELEASE: "false"
          INPUT_STRUCTURED_OUTPUT: "false"
          INPUT_REPORT_PAGE: "true"
          INPUT_VERBOSE_LOGGING: "true"
        run: |
          rm -rf output/generator
          python main.py
          echo "output-path=$PWD/output/generator/mdoc" >> "$GITHUB_OUTPUT"

      - name: Show generated output
        run: ls -lR "${{ steps.generate_living_doc_2.outputs.output-path }}"

      - name: Verify integration test results
        run: pytest tests/integration/validate_outputs_test.py::test_validate_for_test_with_project_mining_and_excluded_project
